"use client";
import { FormEvent, useState } from "react";
import { Eye, EyeOff, Leaf, LockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";
import { Spinner } from "@/components/ui/pending-overlay";
import { useAsyncAction } from "@/lib/use-async-action";
export default function AdminLoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false); const [error, setError] = useState("");
  const { run, pending } = useAsyncAction(async () => { const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const result = await response.json().catch(() => null); if (!response.ok || !result?.success) throw new Error(result?.error || "Gagal masuk."); router.push("/dashboard"); router.refresh(); }, { onError: (e) => setError(e instanceof Error ? e.message : "Gagal masuk.") });
  function submit(e: FormEvent) { e.preventDefault(); setError(""); void run(); }
  return <main className="grid min-h-screen place-items-center bg-[#f5f6f1] px-4 text-[#173d36]"><form onSubmit={submit} className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-xl sm:p-9"><div className="mb-8 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#d9efe1] text-[#176b57]"><Leaf size={25}/></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b84f43]">LabKom internal</p><h1 className="text-2xl font-black">Admin dashboard</h1></div></div><p className="mb-6 text-sm text-[#71807a]">Masuk menggunakan akun admin Supabase.</p><label className="grid gap-2 text-sm font-bold">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required disabled={pending} className="h-12 rounded-xl border border-[#d9ded7] px-4"/></label><label className="mt-4 grid gap-2 text-sm font-bold">Password<span className="relative"><input type={visible ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} required disabled={pending} className="h-12 w-full rounded-xl border border-[#d9ded7] px-4 pr-12"/><button type="button" onClick={() => setVisible(!visible)} className="absolute right-0 top-0 grid h-12 w-12 place-items-center">{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></label>{error && <p role="alert" className="mt-4 rounded-xl bg-[#fde8e5] p-3 text-sm font-bold text-[#a9493e]">{error}</p>}<button disabled={pending} className="mt-6 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#176b57] font-bold text-white">{pending ? <Spinner/> : <LockKeyhole size={17}/>}{pending ? "Memeriksa akun…" : "Masuk dashboard"}</button></form></main>;
}
